// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAP47f3mWlWjynfoCHFrMedTioPKOBosU',
    appId: '1:774181042685:web:31fd86c2ee00f1c21c8194',
    messagingSenderId: '774181042685',
    projectId: 'visualit-82f1a',
    authDomain: 'visualit-82f1a.firebaseapp.com',
    storageBucket: 'visualit-82f1a.firebasestorage.app',
    measurementId: 'G-0C24MBMZ1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnkY_x4fPwEk5WG6PGbOas9KjObIQcsjQ',
    appId: '1:774181042685:android:53e9c3709bf651491c8194',
    messagingSenderId: '774181042685',
    projectId: 'visualit-82f1a',
    storageBucket: 'visualit-82f1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDepnpyzkeCIMRfdTgnV24bj2S6dAhfrvo',
    appId: '1:774181042685:ios:364150b0508499cc1c8194',
    messagingSenderId: '774181042685',
    projectId: 'visualit-82f1a',
    storageBucket: 'visualit-82f1a.firebasestorage.app',
    iosClientId: '774181042685-lqkj2q4mn31p98e07788bh9373le0f2l.apps.googleusercontent.com',
    iosBundleId: 'com.visualit.app.visualit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDepnpyzkeCIMRfdTgnV24bj2S6dAhfrvo',
    appId: '1:774181042685:ios:364150b0508499cc1c8194',
    messagingSenderId: '774181042685',
    projectId: 'visualit-82f1a',
    storageBucket: 'visualit-82f1a.firebasestorage.app',
    iosClientId: '774181042685-lqkj2q4mn31p98e07788bh9373le0f2l.apps.googleusercontent.com',
    iosBundleId: 'com.visualit.app.visualit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAP47f3mWlWjynfoCHFrMedTioPKOBosU',
    appId: '1:774181042685:web:5afa40ccc0ee36c31c8194',
    messagingSenderId: '774181042685',
    projectId: 'visualit-82f1a',
    authDomain: 'visualit-82f1a.firebaseapp.com',
    storageBucket: 'visualit-82f1a.firebasestorage.app',
    measurementId: 'G-C3MTD5GR49',
  );
}
