// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaFkjydamZjWGVlS4Zgpl4WJs34d3L6UE',
    appId: '1:172549574701:web:e43e54112c0e15e2c6e8a4',
    messagingSenderId: '172549574701',
    projectId: 'visualit-b67bc',
    authDomain: 'visualit-b67bc.firebaseapp.com',
    storageBucket: 'visualit-b67bc.firebasestorage.app',
    measurementId: 'G-X04426Z4GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0XX3VhLKZ03hCmkRuzr9sB7JDaqx7ZY',
    appId: '1:172549574701:android:e99ad5603ff199cac6e8a4',
    messagingSenderId: '172549574701',
    projectId: 'visualit-b67bc',
    storageBucket: 'visualit-b67bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2gkQQ8Kd_YKJwjx6WhkdM1SMs7XKSX58',
    appId: '1:172549574701:ios:34aedf28fe650ccec6e8a4',
    messagingSenderId: '172549574701',
    projectId: 'visualit-b67bc',
    storageBucket: 'visualit-b67bc.firebasestorage.app',
    iosClientId: '172549574701-t69sogvndhgti4923oea4eq20mntsmh0.apps.googleusercontent.com',
    iosBundleId: 'com.visualit.app.visualit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2gkQQ8Kd_YKJwjx6WhkdM1SMs7XKSX58',
    appId: '1:172549574701:ios:34aedf28fe650ccec6e8a4',
    messagingSenderId: '172549574701',
    projectId: 'visualit-b67bc',
    storageBucket: 'visualit-b67bc.firebasestorage.app',
    iosClientId: '172549574701-t69sogvndhgti4923oea4eq20mntsmh0.apps.googleusercontent.com',
    iosBundleId: 'com.visualit.app.visualit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaFkjydamZjWGVlS4Zgpl4WJs34d3L6UE',
    appId: '1:172549574701:web:4689651deb231942c6e8a4',
    messagingSenderId: '172549574701',
    projectId: 'visualit-b67bc',
    authDomain: 'visualit-b67bc.firebaseapp.com',
    storageBucket: 'visualit-b67bc.firebasestorage.app',
    measurementId: 'G-WPZ6S2C2R2',
  );
}
